export const adjacentCities = [
    {name: 'San Francisco', adjacentCities: ['Chicago', 'Los Angeles', 'Tokyo', 'Manila']},
    {name: 'Chicago', adjacentCities: ['San Francisco', 'Montreal', 'Atlanta', 'Mexico City', 'Los Angeles']},
    {name: 'Atlanta', adjacentCities: ['Chicago', 'Washington', 'Miami']},
    {name: 'Montreal', adjacentCities: ['Chicago', 'New York', 'Washington']},
    {name: 'New York', adjacentCities: ['Montreal', 'London', 'Madrid', 'Washington']},
    {name: 'Washington', adjacentCities: ['Atlanta', 'Montreal', 'New York', 'Miami']},
    {name: 'London', adjacentCities: ['New York', 'Madrid', 'Paris', 'Essen']},
    {name: 'Madrid', adjacentCities: ['New York', 'London', 'Paris', 'Algiers', 'Sao Paulo']},
    {name: 'Paris', adjacentCities: ['Madrid', 'London', 'Essen', 'Milan', 'Algiers']},
    {name: 'Essen', adjacentCities: ['London', 'St. Petersburg', 'Milan', 'Paris']},
    {name: 'Milan', adjacentCities: ['Paris', 'Essen', 'Istanbul']},
    {name: 'St. Petersburg', adjacentCities: ['Essen', 'Moscow', 'Istanbul']},
    {name: 'Los Angeles', adjacentCities: ['San Francisco', 'Chicago', 'Mexico City', 'Sydney']},
    {name: 'Mexico City', adjacentCities: ['Los Angeles', 'Chicago', 'Miami', 'Bogota', 'Lima']},
    {name: 'Miami', adjacentCities: ['Atlanta', 'Washington', 'Bogota', 'Mexico City']},
    {name: 'Bogota', adjacentCities: ['Mexico City', 'Miami', 'Sao Paulo', 'Buenos Aires', 'Lima']},
    {name: 'Lima', adjacentCities: ['Santiago', 'Mexico City', 'Bogota']},
    {name: 'Santiago', adjacentCities: ['Lima']},
    {name: 'Buenos Aires', adjacentCities: ['Bogota', 'Sao Paulo']},
    {name: 'Sao Paulo', adjacentCities: ['Buenos Aires', 'Bogota', 'Madrid', 'Lagos']},
    {name: 'Lagos', adjacentCities: ['Sao Paulo', 'Khartoum', 'Kinshasha']},
    {name: 'Kinshasha', adjacentCities: ['Lagos', 'Khartoum', 'Johannesburg']},
    {name: 'Johannesburg', adjacentCities: ['Kinshasha', 'Khartoum']},
    {name: 'Khartoum', adjacentCities: ['Johannesburg', 'Kinshasha', 'Lagos', 'Cairo']},
    {name: 'Algiers', adjacentCities: ['Madrid', 'Paris', 'Istanbul', 'Cairo']},
    {name: 'Cairo', adjacentCities: ['Algiers', 'Istanbul', 'Baghdad', 'Riyadh', 'Khartoum']},
    {name: 'Istanbul', adjacentCities: ['Milan', 'St. Petersburg', 'Moscow', 'Baghdad', 'Cairo', 'Algiers']},
    {name: 'Moscow', adjacentCities: ['St. Petersburg', 'Tehran', 'Istanbul']},
    {name: 'Tehran', adjacentCities: ['Moscow', 'Delhi', 'Karachi', 'Baghdad']},
    {name: 'Baghdad', adjacentCities: ['Cairo', 'Istanbul', 'Tehran', 'Karachi', 'Riyadh']},
    {name: 'Riyadh', adjacentCities: ['Cairo', 'Baghdad', 'Karachi']},
    {name: 'Karachi', adjacentCities: ['Riyadh', 'Baghdad', 'Tehran', 'Delhi', 'Mumbai']},
    {name: 'Delhi', adjacentCities: ['Tehran', 'Kolkata', 'Chennai', 'Mumbai', 'Karachi']},
    {name: 'Mumbai', adjacentCities: ['Karachi', 'Delhi', 'Chennai']},
    {name: 'Chennai', adjacentCities: ['Mumbai', 'Delhi', 'Kolkata', 'Bangkok', 'Jakarta']},
    {name: 'Kolkata', adjacentCities: ['Delhi', 'Hong Kong', 'Bangkok', 'Chennai']},
    {name: 'Bangkok', adjacentCities: ['Kolkata', 'Hong Kong', 'Ho Chi Minh City', 'Jakarta', 'Chennai']},
    {name: 'Jakarta', adjacentCities: ['Chennai', 'Bangkok', 'Ho Chi Minh City', 'Sydney']},
    {name: 'Ho Chi Minh City', adjacentCities: ['Bangkok', 'Hong Kong', 'Manila', 'Jakarta']},
    {name: 'Sydney', adjacentCities: ['Jakarta', 'Manila', 'Los Angeles']},
    {name: 'Manila', adjacentCities: ['Sydney', 'Ho Chi Minh City', 'Hong Kong', 'Taipei', 'San Francisco']},
    {name: 'Hong Kong', adjacentCities: ['Kolkata', 'Shanghai', 'Taipei', 'Manila', 'Ho Chi Minh City', 'Bangkok']},
    {name: 'Taipei', adjacentCities: ['Hong Kong', 'Shanghai', 'Osaka', 'Manila']},
    {name: 'Osaka', adjacentCities: ['Taipei', 'Tokyo']},
    {name: 'Tokyo', adjacentCities: ['Osaka', 'Shanghai', 'Seoul', 'San Francisco']},
    {name: 'Seoul', adjacentCities: ['Beijing', 'Tokyo', 'Shanghai']},
    {name: 'Beijing', adjacentCities: ['Shanghai', 'Seoul']},
    {name: 'Shanghai', adjacentCities: ['Beijing', 'Seoul', 'Tokyo', 'Taipei', 'Hong Kong']},
]