export const cities = [
    {name: 'San Francisco', color: 'blue', lat: 37.77, lng: -122.419, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Chicago', 'Los Angeles', 'Tokyo', 'Manila']},
    {name: 'Chicago', color: 'blue', lat: 41.878, lng: -87.6298, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['San Francisco', 'Montreal', 'Atlanta', 'Mexico City', 'Los Angeles']},
    {name: 'Atlanta', color: 'blue', lat: 33.749, lng: -84.388, researchStation: true, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Chicago', 'Washington', 'Miami'], players: [1, 2]},
    {name: 'Montreal', color: 'blue', lat: 45.5, lng: -73.567, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Chicago', 'New York', 'Washington']},
    {name: 'New York', color: 'blue', lat: 40.713, lng: -74.006, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Montreal', 'London', 'Madrid', 'Washington']},
    {name: 'Washington', color: 'blue', lat: 38.907, lng: -77.037, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Atlanta', 'Montreal', 'New York', 'Miami']},
    {name: 'London', color: 'blue', lat: 51.507, lng: -0.1278, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['New York', 'Madrid', 'Paris', 'Essen']},
    {name: 'Madrid', color: 'blue', lat: 40.4168, lng: -3.7038, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['New York', 'London', 'Paris', 'Algiers', 'Sao Paulo']},
    {name: 'Paris', color: 'blue', lat: 48.8566, lng: 2.3522, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Madrid', 'London', 'Essen', 'Milan', 'Algiers']},
    {name: 'Essen', color: 'blue', lat: 51.4556, lng: 7.0116, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['London', 'St. Petersburg', 'Milan', 'Paris']},
    {name: 'Milan', color: 'blue', lat: 45.4654, lng: 9.1859, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Paris', 'Essen', 'Istanbul']},
    {name: 'St. Petersburg', color: 'blue', lat: 59.9343, lng: 30.3351, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Essen', 'Moscow', 'Istanbul']},
    {name: 'Los Angeles', color: 'yellow', lat: 34.0522, lng: -118.2437, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['San Francisco', 'Chicago', 'Mexico City', 'Sydney']},
    {name: 'Mexico City', color: 'yellow', lat: 19.4326, lng: -99.1332, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Los Angeles', 'Chicago', 'Miami', 'Bogota', 'Lima']},
    {name: 'Miami', color: 'yellow', lat: 25.7617, lng: -80.1918, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Atlanta', 'Washington', 'Bogota', 'Mexico City']},
    {name: 'Bogota', color: 'yellow', lat: 4.7110, lng: -74.0721, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Mexico City', 'Miami', 'Sao Paulo', 'Buenos Aires', 'Lima']},
    {name: 'Lima', color: 'yellow', lat: -12.0464, lng: -77.0428, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Santiago', 'Mexico City', 'Bogota']},
    {name: 'Santiago', color: 'yellow', lat: -33.4489, lng: -70.6693, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Lima']},
    {name: 'Buenos Aires', color: 'yellow', lat: -34.6037, lng: -58.3816, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Bogota', 'Sao Paulo']},
    {name: 'Sao Paulo', color: 'yellow', lat: -23.5505, lng: -46.6333, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Buenos Aires', 'Bogota', 'Madrid', 'Lagos']},
    {name: 'Lagos', color: 'yellow', lat: 6.5244, lng: 3.3792, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Sao Paulo', 'Khartoum', 'Kinshasha']},
    {name: 'Kinshasha', color: 'yellow', lat: -4.4419, lng: 15.2663, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Lagos', 'Khartoum', 'Johannesburg']},
    {name: 'Johannesburg', color: 'yellow', lat: -26.2041, lng: 28.0473, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Kinshasha', 'Khartoum']},
    {name: 'Khartoum', color: 'yellow', lat: 15.5007, lng: 32.5599, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Johannesburg', 'Kinshasha', 'Lagos', 'Cairo']},
    {name: 'Algiers', color: 'black', lat: 36.7538, lng: 3.0588, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Madrid', 'Paris', 'Istanbul', 'Cairo']},
    {name: 'Cairo', color: 'black', lat: 30.0444, lng: 31.2357, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Algiers', 'Istanbul', 'Baghdad', 'Riyadh', 'Khartoum']},
    {name: 'Istanbul', color: 'black', lat: 41.0082, lng: 28.9784, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Milan', 'St. Petersburg', 'Moscow', 'Baghdad', 'Cairo', 'Algiers']},
    {name: 'Moscow', color: 'black', lat: 55.7558, lng: 37.6173, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['St. Petersburg', 'Tehran', 'Istanbul']},
    {name: 'Tehran', color: 'black', lat: 35.6892, lng: 51.3890, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Moscow', 'Delhi', 'Karachi', 'Baghdad']},
    {name: 'Baghdad', color: 'black', lat: 33.3128, lng: 44.3615, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Cairo', 'Istanbul', 'Tehran', 'Karachi', 'Riyadh']},
    {name: 'Riyadh', color: 'black', lat: 24.7136, lng: 46.6753, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Cairo', 'Baghdad', 'Karachi']},
    {name: 'Karachi', color: 'black', lat: 24.8615, lng: 67.0099, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Riyadh', 'Baghdad', 'Tehran', 'Delhi', 'Mumbai']},
    {name: 'Delhi', color: 'black', lat: 28.7041, lng: 77.1025, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Tehran', 'Kolkata', 'Chennai', 'Mumbai', 'Karachi']},
    {name: 'Mumbai', color: 'black', lat: 19.0760, lng: 72.8777, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Karachi', 'Delhi', 'Chennai']},
    {name: 'Chennai', color: 'black', lat: 13.0827, lng: 80.2707, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Mumbai', 'Delhi', 'Kolkata', 'Bangkok', 'Jakarta']},
    {name: 'Kolkata', color: 'black', lat: 22.5726, lng: 88.3639, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Delhi', 'Hong Kong', 'Bangkok', 'Chennai']},
    {name: 'Bangkok', color: 'red', lat: 13.7563, lng: 100.5018, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Kolkata', 'Hong Kong', 'Ho Chi Minh City', 'Jakarta', 'Chennai']},
    {name: 'Jakarta', color: 'red', lat: -6.1745, lng: 106.8227, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Chennai', 'Bangkok', 'Ho Chi Minh City', 'Sydney']},
    {name: 'Ho Chi Minh City', color: 'red', lat: 10.8231, lng: 106.6297, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Bangkok', 'Hong Kong', 'Manila', 'Jakarta']},
    {name: 'Sydney', color: 'red', lat: -33.8688, lng: 151.2093, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Jakarta', 'Manila', 'Los Angeles']},
    {name: 'Manila', color: 'red', lat: 14.5995, lng: 120.9842, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Sydney', 'Ho Chi Minh City', 'Hong Kong', 'Taipei', 'San Francisco']},
    {name: 'Hong Kong', color: 'red', lat: 22.3964, lng: 114.1095, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Kolkata', 'Shanghai', 'Taipei', 'Manila', 'Ho Chi Minh City', 'Bangkok']},
    {name: 'Taipei', color: 'red', lat: 25.0330, lng: 121.5654, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Hong Kong', 'Shanghai', 'Osaka', 'Manila']},
    {name: 'Osaka', color: 'red', lat: 34.6937, lng: 135.5022, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Taipei', 'Tokyo']},
    {name: 'Tokyo', color: 'red', lat: 35.6895, lng: 139.6917, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Osaka', 'Shanghai', 'Seoul', 'San Francisco']},
    {name: 'Seoul', color: 'red', lat: 37.5665, lng: 126.9780, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Beijing', 'Tokyo', 'Shanghai']},
    {name: 'Beijing', color: 'red', lat: 39.9042, lng: 116.4074, researchStation: false, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Shanghai', 'Seoul']},
    {name: 'Shanghai', color: 'red', lat: 31.2304, lng: 121.4737, researchStation: true, cubes:{black: 0, blue: 0, red: 0, yellow: 0}, adjacentCities: ['Beijing', 'Seoul', 'Tokyo', 'Taipei', 'Hong Kong']},
]