export const playerDeck = [
    {name: 'Lagos', color: 'yellow', population: 11547000, type: 'city'},
    {name: 'Washington', color: 'blue', population: 4679000, type: 'city'},
    {name: 'Santiago', color: 'yellow', population: 6015000, type: 'city'},
    {name: 'Milan', color: 'blue', population: 5232000, type: 'city'},
    {name: 'Ho Chi Minh City', color: 'red', population: 8314000, type: 'city'},
    {name: 'Riyadh', color: 'black', population: 5037000, type: 'city'},
    {name: 'Chicago', color: 'blue', population: 9121000, type: 'city'},
    {name: 'Chennai', color: 'black', population: 8865000, type: 'city'},
    {name: 'Buenos Aires', color: 'yellow', population: 13639000, type: 'city'},
    {name: 'Khartoum', color: 'yellow', population: 4887000, type: 'city'},
    {name: 'Algiers', color: 'black', population: 2946000, type: 'city'},
    {name: 'Jakarta', color: 'red', population: 26063000, type: 'city'},
    {name: 'Istanbul', color: 'black', population: 13576000, type: 'city'},
    {name: 'Bogota', color: 'yellow', population: 8702000, type: 'city'},
    {name: 'Lima', color: 'yellow', population: 9121000, type: 'city'},
    {name: 'Los Angeles', color: 'yellow', population: 149000, type: 'city'},
    {name: 'Kinshasha', color: 'yellow', population: 9046000, type: 'city'},
    {name: 'Kolkata', color: 'black', population: 14374000, type: 'city'},
    {name: 'Delhi', color: 'black', population: 22242000, type: 'city'},
    {name: 'Tehran', color: 'black', population: 7419000, type: 'city'},
    {name: 'Sydney', color: 'red', population: 3785000, type: 'city'},
    {name: 'Shanghai', color: 'red', population: 13482000, type: 'city'},
    {name: 'Taipei', color: 'red', population: 8338000, type: 'city'},
    {name: 'Hong Kong', color: 'red', population: 7106000, type: 'city'},
    {name: 'Bangkok', color: 'red', population: 7151000, type: 'city'},
    {name: 'Mumbai', color: 'black', population: 1691000, type: 'city'},
    {name: 'London', color: 'blue', population: 8586000, type: 'city'},
    {name: 'San Francisco', color: 'blue', population: 5864000, type: 'city'},
    {name: 'Johannesburg', color: 'yellow', population: 3888000, type: 'city'},
    {name: 'Atlanta', color: 'blue', population: 4715000, type: 'city'},
    {name: 'Paris', color: 'blue', population: 10755000, type: 'city'},
    {name: 'Miami', color: 'yellow', population: 5582000, type: 'city'},
    {name: 'Baghdad', color: 'black', population: 6204000, type: 'city'},
    {name: 'Essen', color: 'blue', population: 575000, type: 'city'},
    {name: 'Madrid', color: 'blue', population: 5427000, type: 'city'},
    {name: 'Mexico City', color: 'yellow', population: 19463000, type: 'city'},
    {name: 'Seoul', color: 'red', population: 22547000, type: 'city'},
    {name: 'New York', color: 'blue', population: 20464000, type: 'city'},
    {name: 'Karachi', color: 'black', population: 20711000, type: 'city'},
    {name: 'Tokyo', color: 'red', population: 13189000, type: 'city'},
    {name: 'Beijing', color: 'red', population: 17311000, type: 'city'},
    {name: 'Sao Paulo', color: 'yellow', population: 20186000, type: 'city'},
    {name: 'Manila', color: 'red', population: 20767000, type: 'city'},
    {name: 'Moscow', color: 'black', population: 15512000, type: 'city'},
    {name: 'Osaka', color: 'red', population: 2871000, type: 'city'},
    {name: 'St. Petersburg', color: 'blue', population: 4879000, type: 'city'},
    {name: 'Cairo', color: 'black', population: 14718000, type: 'city'},
    {name: 'Montreal', color: 'blue', population: 3429000, type: 'city'},
]

export const epidemicCard = {name: 'Epidemic', color: 'green', type: 'epidemic'}